# Generated by Django 5.2.4 on 2026-04-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
